name: Build

on:
  push:
    branches: [ "main", "test_ci" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Idk if actually useful
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
    
    - name: Setup dbus and secrets API for tests
      run: cd misc && docker compose up -d

    - name: Test
      run: dotnet test --no-build --verbosity normal
